#!/var/task/native/bin/php
<?php declare(strict_types=1);

use Bref\Runtime\LambdaRuntime;
use Bref\Runtime\PhpFpm;

ini_set('display_errors', '1');
error_reporting(E_ALL);

$appRoot = getenv('LAMBDA_TASK_ROOT');

require $appRoot . '/vendor/autoload.php';

$lambdaRuntime = LambdaRuntime::fromEnvironmentVariable();

$handler = $appRoot . '/' . getenv('_HANDLER');
if (! is_file($handler)) {
    $lambdaRuntime->failInitialization("Handler `$handler` doesn't exist");
}

$phpFpm = new PhpFpm($handler, '/var/task/native/bref/etc/php-fpm.conf');
try {
    $phpFpm->start();
} catch (\Throwable $e) {
    $lambdaRuntime->failInitialization('Error while starting PHP-FPM', $e);
}

while (true) {
    $lambdaRuntime->processNextEvent(function ($event) use ($phpFpm): array {
        // We need to take event.body because at ZEIT Now structure
        $body = [];

        if (isset($event['Action'])) {
            // event { method, path, headers, encoding, body }
            $body = json_decode($event['body'], true);
            $body['httpMethod'] = $body['method'];
            $body['isBase64Encoded'] = ($body['encoding'] ?? null) === 'base64';
        } else {
            // event { httpMethod, path, headers, body }
            $body = json_decode($event['body'], true);
        }

        $response = $phpFpm->proxy($body);
        return $response->toApiGatewayFormat();
    });

    try {
        $phpFpm->ensureStillRunning();
    } catch (\Throwable $e) {
        echo $e->getMessage();
        exit(1);
    }
}
